### ISSUE TITLE
Request Object

### ISSUE THREAD

**Issue by yehandesilva** [Aranesh22/SYSC3303A#8]
- Object of this class gets instansiated by floor for each request
- Should have a getBytes() method so Floor can send this to Elevator (UDP)

**Comment by yehandesilva** [comment]
Not doing UDP anymore, but UML should explain this class well.

**Comment by Lindiks** [comment]
Request class has been implemented for iteration 1
- constructor might need refactoring but it currently follows its UML representation
- Also added in the elevatorId variable + getter as a way to track the "requester" (for when we have multiple elevators in the future)
